M48
; DRILL file {KiCad 8.0.2} date 2024-05-21T13:11:15+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-21T13:11:15+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.5509Y-6.0644
X6.1434Y-6.0644
T2
X5.4159Y-4.5894
X6.2859Y-2.0894
M30
